apply plugin: 'com.android.library'

android {
    compileSdk rootProject.ext.compileSdkVersion
    namespace "org.opencv"

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }
}

// The OpenCV AAR must be placed at android/opencv/libs/opencv-4.10.0.aar
// Download from: https://github.com/opencv/opencv/releases (Android pack)
repositories {
    flatDir { dirs 'libs' }
}

dependencies {
    api(name: 'opencv-4.10.0', ext: 'aar')
}
